### ISSUE TITLE
How to specify the relative size of ImwWindow in ImwWindowManager::Dock()

### ISSUE THREAD

**Issue by vinjn** [thennequin/ImWindow#1]
The default layout.

![image](https://cloud.githubusercontent.com/assets/558657/11164331/7e88fa90-8b28-11e5-976e-6b373b553b57.png)

My intended layout. 

![image](https://cloud.githubusercontent.com/assets/558657/11164332/86c103e2-8b28-11e5-99d9-70faed02d553.png)

**Comment by thennequin** [comment]
I added this functionnality.
Check commit c8b15fbd1478165bae6180fa966145de20a5ee69 and c91382e55245db478c4b3382e4f3be89e85ff84b

``` C
    oMgr.Dock(pWindow1);
    oMgr.DockWith(pWindow2, pWindow1, E_DOCK_ORIENTATION_LEFT, 0.75f);
    oMgr.DockWith(pWindow3, pWindow2, E_DOCK_ORIENTATION_TOP, 0.75f);
    oMgr.DockWith(pWindow4, pWindow3, E_DOCK_ORIENTATION_LEFT, 0.25f);
    oMgr.DockWith(pWindow5, pWindow4, E_DOCK_ORIENTATION_CENTER);
```

![dockratio](https://cloud.githubusercontent.com/assets/2106096/11171732/80eb37ec-8bf7-11e5-989b-66da61593dd6.jpg)

**Comment by vinjn** [comment]
Awesome, thx.
