### ISSUE TITLE
bugged test?

### ISSUE THREAD

**Issue by elect86** [thennequin/ImWindow#15]
So, I finally succeeded to build it.

But if I run the test and click on the first `Platform window`

![Imgur](http://i.imgur.com/JcCzcaF.png)

Also the other `Platform window` gets highlighted and I see also some sparse ticks

Is the test bugged?

**Comment by thennequin** [comment]
Yes it's a bug, but it's really linked to an ImGui bug.
I will fix the sample for avoid the problem.

**Comment by thennequin** [comment]
I update the sample.
