### ISSUE TITLE
Undefined Identifier ImGuiState

### ISSUE THREAD

**Issue by JoshParker11** [thennequin/ImWindow#16]
Hi there, got everything to build fine expect the last couple of errors which have to do with ImGuiState not being defined, Is it a problem with the version of ImGui im using, I'm pretty sure I have all of the newest stuff? Thank you!

![image](https://user-images.githubusercontent.com/16564007/29493065-44dbb136-8543-11e7-8d56-339a56866893.png)

![image](https://user-images.githubusercontent.com/16564007/29493072-6403954c-8543-11e7-88d8-e7d9adc2cce6.png)

**Comment by thennequin** [comment]
ImWindow use ImGui with the version 1.48, you probably updated your ImGui to a newer version.
If you want to use the last version of ImGui, try the branch **Issue7**, but this branch is not merged with the lasts **master** commit.

**Comment by JoshParker11** [comment]
Thank you very much, that was the solution!
Awesome Addon!

**Comment by thennequin** [comment]
Ok, so I close the issue.
