### ISSUE TITLE
Unresolved Externals in DX11 example project

### ISSUE THREAD

**Issue by JoshParker11** [thennequin/ImWindow#18]
Hi, sorry to bug you again, thought I had it worked out, got everything to build at one point, until I tried to build the example project, I got these unresolved externals:
![image](https://user-images.githubusercontent.com/16564007/29595208-f0678272-876a-11e7-933d-359306ff8638.png)

I'm building in debug, x86

**Comment by thennequin** [comment]
No problem for me with Visual Studio 2012, debug Win32.
Try in x64.

**Comment by thennequin** [comment]
You solved your problems?

**Comment by JoshParker11** [comment]
Sorry just got back into the country and around internet. Ya, I ended up just changing the target machine type to 64 bit then changed it back to 32 and it worked fine. I don't know, settings ended up being the same as they started, must have just been a weird build thing.

**Comment by thennequin** [comment]
Ok so i close the issue?
