### ISSUE TITLE
Working example

### ISSUE THREAD

**Issue by ghost** [thennequin/ImWindow#2]
Hi,

It looks interesting, but how the docking window works ?

Do you have some example code that show how to use it in our own application ?

Thanks

**Comment by thennequin** [comment]
Hi,

you can find the exemple in **ImWindowDX11/main.cpp**
if you already have a render with ImGui, you can just instantiate **ImwWindowManager** and call **Run** from  this instance on each frame, it call ImGui::Render() automaticly, so ne need to call it.

**Comment by ghost** [comment]
Thanks,

Does it work on Linux & Mac OS ?

On Windows, is it only for DirectX or also for OpenGL ?

**Comment by thennequin** [comment]
I never test but it should works for only one window (no multi window) if you just use ImwWindowManager, or you can try to create implementation for your platform, like in the DX11 exemple, override ImwWindowManager and ImwPlatformWindow.
