### ISSUE TITLE
Help to build this library.

### ISSUE THREAD

**Issue by Shan0x228** [thennequin/ImWindow#26]
Hello, i can't build this library, have errors. Im link(in project settings) and download all external dependencies but have errors. Im use Visual Studio 2017 Community.
Screenshot:
![default](https://user-images.githubusercontent.com/31966129/35670133-91cc9cf8-0748-11e8-8bed-dc1ae1b68372.png)

**Comment by thennequin** [comment]
Hi, sorry but I don't understand your linking errors (it's Russian?), try to get a way to retrieve error in English so that I can help you.
But I think you need to retrieve the right commit for the ImGui submodule.
ImWindow is compatible only with ImGui 1.50.

**Comment by ChemistAion** [comment]
It is quite straight forward to upgrade @thennequin ImWindow to work with the latest @ocornut ImGui.

@Shan0x228: You could check my customized ImWindow with all the necessary updates and changes for the reference:
[https://gist.github.com/ChemiaAion/60d6ff71afc5f0367ccdea64b45acb34](https://gist.github.com/ChemiaAion/60d6ff71afc5f0367ccdea64b45acb34)
I shortened mainly ImwWindowManager and ImwPlatformWindow to work only with my back-end but this (and other small cuts/changes) should not interference with an upgrade too much.

**Comment by Shan0x228** [comment]
Thanks @ChemiaAion and @thennequin . I fix it by download ImGUI 1.50, my mistake :(.
