### ISSUE TITLE
The close button on the title bar cannot be closed 

### ISSUE THREAD

**Issue by zhouxs1023** [thennequin/ImWindow#33]
The close button on the title bar cannot be closed as below;

![360--16410124200844](https://user-images.githubusercontent.com/905931/70635081-418d9700-1c6e-11ea-902b-6330039280b4.png)
but  menuitem "Exit" can close app!

**Comment by thennequin** [comment]
It's a normal behaviour, you need to click on the **Close** button of MyImwWIndow3 (in the middle of the screen).

**Comment by zhouxs1023** [comment]
Thank you very much. The problem has been solved
