### ISSUE TITLE
Drawing scenes based on opengl in ImwWindow

### ISSUE THREAD

**Issue by WangMuMuMuMuMu** [thennequin/ImWindow#45]
Hi, thank you for this great project
want to ask you, how to draw 3D images based on opengl in a certain ImwWindow? GLFWwindow* seems unable to obtain and bind

**Comment by thennequin** [comment]
Hi, you need to render your 3D scene into a Texture/RenderTarget, then display the Texture via ImGui::Image, in an ImWindow::OnGui.
